apiVersion: apps/v1
kind: Deployment
metadata:
  name: award-adminpanel
  labels:
    app: award-adminpanel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: award-adminpanel
  template:
    metadata:
      labels:
        app: award-adminpanel
    spec:
      # Secret to pull image from private Nexus Docker registry
      imagePullSecrets:
        - name: nexus-registry-secret

      containers:
        - name: award-adminpanel
          image: 192.168.11.21:8085/repository/docker_registry/award-adminpanel:26
          ports:
            - containerPort: 5173   # Frontend port inside the container
            - containerPort: 8385   # Backend port inside the container
          # (Optional) add env variables, resource limits, volume mounts here as needed
---
apiVersion: v1
kind: Service
metadata:
  name: award-adminpanel-service
spec:
  type: NodePort
  selector:
    app: award-adminpanel
  ports:
    - name: frontend
      port: 5173             # Service port exposed inside the cluster
      targetPort: 5173       # Container port to forward traffic to
      nodePort: 30173        # NodePort to expose service externally on nodes

    - name: backend
      port: 8385             # Service port for backend inside cluster
      targetPort: 8385       # Backend container port
      nodePort: 30385        # NodePort for external access to backend
